databases:
  - name: izedb
    databaseName: izedb
    user: izedb_user
    plan: starter
    region: oregon
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    postgresMajorVersion: "16"
services:
  - type: web
    name: ize
    runtime: node
    repo: https://github.com/ize-app/ize
    plan: starter
    branch: main
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: izedb
          property: connectionString
    region: oregon
    buildCommand: npm install && npm run codegen && cd apps/backend && npx prisma migrate deploy && cd ../.. &&  npm run build
    startCommand: cd apps/backend && npm run start:prod
version: "1"