databases:
  - name: izedb
    databaseName: izedb
    user: izedb_user
    plan: starter
    region: oregon
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    postgresMajorVersion: "16"
services:
  - type: web
    name: ize
    runtime: node
    repo: https://github.com/ize-app/ize
    plan: starter
    branch: main
    envVars:
      - fromGroup: ize-env-group
    region: oregon
    buildCommand: npm install && npm run codegen && cd apps/backend && npm run prisma-migrate-deploy && npm run prisma-generate && cd ../.. &&  npm run build
    startCommand: cd apps/backend && npm run start:prod
  - type: cron
    name: ize-cron
    schedule: "*/10 * * * *" # every 10 minutes
    runtime: node
    repo: https://github.com/ize-app/ize
    plan: standard
    branch: main
    envVars:
      - fromGroup: ize-env-group
    region: oregon
    buildCommand: npm install && npm run codegen && cd apps/backend && npm run prisma-migrate-deploy && npm run prisma-generate && cd ../.. &&  npm run build
    startCommand: cd apps/backend && npm run cron
version: "1"
envVarGroups:
  - name: ize-env-group
    envVars:
      - key: MODE
        value: "production"
      - key: LOCAL_URL
        value: "http://127.0.0.1"
      - key: PROD_URL
        value: "https://ize.space"
      - key: PROD_RENDER_URL
        value: "https://ize.onrender.com"
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: OPEN_AI_KEY
        sync: false
      - key: ALCHEMY_API_KEY
        sync: false
      - key: STYTCH_PROJECT_ID
        sync: false
      - key: STYTCH_PROJECT_SECRET
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: ENCRYPTION_IV
        sync: false
      - key: DISCORD_IZE_BOT_API_TOKEN
        sync: false
      - key: SENTRY_AUTH_TOKEN
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
